# ==========================================================
# Experiment
# ==========================================================

experiment_name: "Thermal SR"
run_name: "EDSR Baseline"

seed: 42

# ==========================================================
# Dataset
# ==========================================================

data_root: "/home/sanjeet/ai_workspace/IR image enhancement and colorization/IR-colorization-BAH2026/output/patches"

split_root: "/home/sanjeet/ai_workspace/IR image enhancement and colorization/IR-colorization-BAH2026/splits"

# ==========================================================
# DataLoader
# ==========================================================

batch_size: 8

num_workers: 4

pin_memory: true

# persistent_workers: true

# ==========================================================
# Model
# ==========================================================

num_features: 64

num_blocks: 8

scale_factor: 2

# ==========================================================
# Training
# ==========================================================

max_epochs: 5

learning_rate: 1e-4

weight_decay: 1e-4

# ==========================================================
# Loss
# ==========================================================

alpha: 0.8

beta: 0.2

# ==========================================================
# Scheduler
# ==========================================================

eta_min: 1e-6

# ==========================================================
# Trainer
# ==========================================================

accelerator: "auto"

devices: 1

precision: "16-mixed"

# ==========================================================
# Logging
# ==========================================================

log_every_n_steps: 10

# ==========================================================
# Checkpointing
# ==========================================================

monitor: "val_psnr"

mode: "max"

save_top_k: 3

patience: 15

min_delta: 0.01